baseURL = "/"
languageCode = "en-us"
ignoreErrors = ["error-remote-getjson"]
title = "Aashiyana of Pamela Santanu"
theme = "santm-bulma_v2"
enableEmoji = true
[wordCount]
other = "{{ .WordCount }} words"
[params]
  author = "Santanu Misra"
  description = "Rumblings on life, travel or anything under sun"
  [[params.FootMenu]]
    medium = "rss"
    icon = "fa fa-rss-square"
    link = "/index.xml"
  [[params.FootMenu]]
    medium = "facebook"
    icon = "fab fa-facebook-square"
    link = "https://www.facebook.com/santm"
  [[params.FootMenu]]
    medium = "instagram"
    icon = "fab fa-instagram-square"
    link = "https://www.instagram.com/s.a.n.t.m/"
  [[params.FootMenu]]
    medium = "linkedin"
    icon = "fab fa-linkedin"
    link = "https://www.linkedin.com/in/santm/"
  [[params.FootMenu]]
    medium = "tumblr"
    icon = "fab fa-tumblr-square"
    link = "https://pamelascreation.tumblr.com/"

  [[params.RightMenu]]
    medium = "Blog"
    icon = "far fa-newspaper fa-2x"
    link = "/blog"
  [[params.RightMenu]]
    medium = "Birds & Wildlife"
    icon = "fa fa-paw fa-2x"
    link = "/bird-wildlife"
  [[params.RightMenu]]
    medium = "Travel Picture"
    icon = "fa fa-camera-retro fa-2x"
    link = "/album"  
  [[params.RightMenu]]
    medium = "About"
    icon = "fa fa-user fa-2x"
    link = "/about"
  [[params.RightMenu]]
    medium = "Contact"
    icon = "fa fa-id-card fa-2x"
    link = "/contact"
  [[params.RightMenu]]
    medium = "Tags"
    icon = "fa fa-tags fa-2x"
    link = "/tags"
[taxonomies]
    year = "year"
    month = "month"
    tags = "tags"
    category = "categories"
[permalinks]
    post = "/posts/:year/:month/:slug/"
    year = "/posts/:slug/"
    month = "/posts/:slug/"
[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = "categories"
  weight = 100
